package actions.weibo;

import java.util.HashMap;
import java.util.Map;

import org.apache.commons.lang3.StringUtils;

public class WeiboErrorCodeAction {
    
    private static final Map<Integer, String> WeiboErrorCodeMap = new HashMap<Integer, String>();
    
    static {
        WeiboErrorCodeMap.put(10001, "系统错误");
        WeiboErrorCodeMap.put(10002, "服务端资源不可用");
        WeiboErrorCodeMap.put(10003, "远程服务出错");
        WeiboErrorCodeMap.put(10005, "该资源需要appkey拥有更高级的授权");
        WeiboErrorCodeMap.put(10006, "缺少 source参数(appkey)");
        WeiboErrorCodeMap.put(10007, "不支持的 MediaType (%s)");
        WeiboErrorCodeMap.put(10008, "错误:参数错误，请参考API文档");
        WeiboErrorCodeMap.put(10009, "任务过多，系统繁忙");
        WeiboErrorCodeMap.put(10010, "任务超时");
        WeiboErrorCodeMap.put(10011, "RPC错误");
        WeiboErrorCodeMap.put(10012, "非法请求");
        WeiboErrorCodeMap.put(10013, "不合法的微博用户");
        WeiboErrorCodeMap.put(10014, "第三方应用访问api接口权限受限制");
        WeiboErrorCodeMap.put(10016, "错误:缺失必选参数:%s，请参考API文档");
        WeiboErrorCodeMap.put(10017, "错误:参数值非法,希望得到 (%s),实际得到 (%s)，请参考API文档");
        WeiboErrorCodeMap.put(10018, "请求长度超过限制");
        WeiboErrorCodeMap.put(10020, "接口不存在");
        WeiboErrorCodeMap.put(10021, "请求的HTTP METHOD不支持");
        WeiboErrorCodeMap.put(10022, "IP请求超过上限");
        WeiboErrorCodeMap.put(10023, "用户请求超过上限");
        WeiboErrorCodeMap.put(10024, "用户请求接口%s超过上限");
        WeiboErrorCodeMap.put(10025, "内部接口参数错误");
        WeiboErrorCodeMap.put(10026, "该接口已经废弃");
        WeiboErrorCodeMap.put(20001, "IDS参数为空");
        WeiboErrorCodeMap.put(20002, "uid参数为空");
        WeiboErrorCodeMap.put(20003, "用户不存在");
        WeiboErrorCodeMap.put(20005, "不支持的图片类型,仅仅支持JPG,GIF,PNG");
        WeiboErrorCodeMap.put(20006, "图片太大");
        WeiboErrorCodeMap.put(20007, "请确保使用multpart上传了图片");
        WeiboErrorCodeMap.put(20008, "内容为空");
        WeiboErrorCodeMap.put(20009, "id列表太长了");
        WeiboErrorCodeMap.put(20012, "输入文字太长，请确认不超过140个字符");
        WeiboErrorCodeMap.put(20013, "输入文字太长，请确认不超过300个字符");
        WeiboErrorCodeMap.put(20014, "传入参数有误，请再调用一次");
        WeiboErrorCodeMap.put(20016, "发微博太多啦，休息一会儿吧");
        WeiboErrorCodeMap.put(20017, "你刚刚已经发送过相似内容了哦，先休息一会吧");
        WeiboErrorCodeMap.put(20019, "不要太贪心哦，发一次就够啦");
        WeiboErrorCodeMap.put(20023, "很抱歉，此功能暂时无法使用，如需帮助请联系@微博客服 或者致电客服电话400 690 0000");
        WeiboErrorCodeMap.put(20031, "需要弹出验证码");
        WeiboErrorCodeMap.put(20032, "微博发布成功。目前服务器数据同步可能会有延迟，请耐心等待1-2分钟。谢谢");
        WeiboErrorCodeMap.put(20033, "登陆状态异常");
        WeiboErrorCodeMap.put(20038, "您刚才已经发过相似的内容啦，建议您第二天再尝试！");
        WeiboErrorCodeMap.put(20044, "可发表，但是需要弹出蒙层");
        WeiboErrorCodeMap.put(20045, "不可发表，需要弹出蒙层");
        WeiboErrorCodeMap.put(20101, "不存在的微博");
        WeiboErrorCodeMap.put(20102, "不是你发布的微博");
        WeiboErrorCodeMap.put(20103, "不能转发自己的微博");
        WeiboErrorCodeMap.put(20109, "微博 id为空");
        WeiboErrorCodeMap.put(20111, "不能发布相同的微博");
        WeiboErrorCodeMap.put(20112, "由于作者隐私设置，你没有权限查看此微博");
        WeiboErrorCodeMap.put(20114, "标签名太长");
        WeiboErrorCodeMap.put(20115, "标签不存在");
        WeiboErrorCodeMap.put(20116, "标签已存在");
        WeiboErrorCodeMap.put(20117, "最多200个标签");
        WeiboErrorCodeMap.put(20118, "最多5个标签");
        WeiboErrorCodeMap.put(20119, "标签搜索失败");
        WeiboErrorCodeMap.put(20120, "由于作者设置了可见性，你没有权限转发此微博");
        WeiboErrorCodeMap.put(20121, "visible参数非法");
        WeiboErrorCodeMap.put(20122, "应用不存在");
        WeiboErrorCodeMap.put(20123, "最多屏蔽200个应用");
        WeiboErrorCodeMap.put(20124, "最多屏蔽500条微博");
        WeiboErrorCodeMap.put(20125, "没有屏蔽过此应用");
        WeiboErrorCodeMap.put(20126, "不能屏蔽新浪应用");
        WeiboErrorCodeMap.put(20127, "已添加了此屏蔽");
        WeiboErrorCodeMap.put(20128, "删除屏蔽失败");
        WeiboErrorCodeMap.put(20129, "没有屏蔽任何应用");
        WeiboErrorCodeMap.put(20130, "由于作者隐私设置，你没有权限评论此微博");
        WeiboErrorCodeMap.put(20132, "抱歉，该内容暂时无法查看。如需帮助，请联系客服");
        WeiboErrorCodeMap.put(20133, "您不是会员，或者已过期，只有会员才能屏蔽应用");
        WeiboErrorCodeMap.put(20134, "分组不存在");
        WeiboErrorCodeMap.put(20135, "源微博已被删除");
        WeiboErrorCodeMap.put(20136, "非会员发表定向微博，分组成员数最多200");
        WeiboErrorCodeMap.put(20201, "不存在的微博评论");
        WeiboErrorCodeMap.put(20203, "不是你发布的评论");
        WeiboErrorCodeMap.put(20204, "评论ID为空");
        WeiboErrorCodeMap.put(20206, "作者只允许关注用户评论");
        WeiboErrorCodeMap.put(20207, "作者只允许可信用户评论");
        WeiboErrorCodeMap.put(20401, "域名不存在");
        WeiboErrorCodeMap.put(20402, "verifier错误");
        WeiboErrorCodeMap.put(20403, "屏蔽用户列表中存在此uid");
        WeiboErrorCodeMap.put(20404, "屏蔽用户列表中不存在此uid");
        WeiboErrorCodeMap.put(20405, "uid对应用户不是登录用户的好友");
        WeiboErrorCodeMap.put(20406, "屏蔽用户个数超出上限");
        WeiboErrorCodeMap.put(20407, "没有合适的uid");
        WeiboErrorCodeMap.put(20408, "从feed屏蔽列表中，处理用户失败");
        WeiboErrorCodeMap.put(20409, "当前用户不存在置顶微博");
        WeiboErrorCodeMap.put(20410, "设置置顶微博失败");
        WeiboErrorCodeMap.put(20411, "该微博不是你的微博");
        WeiboErrorCodeMap.put(20412, "当前用户已经试用微博置顶功能，不能再试用");
        WeiboErrorCodeMap.put(20413, "此微博不是置顶微博");
        WeiboErrorCodeMap.put(20414, "此微博是当前置顶微博");
        WeiboErrorCodeMap.put(20501, "错误:source_user 或者target_user用户不存在");
        WeiboErrorCodeMap.put(20502, "必须输入目标用户id或者 screen_name");
        WeiboErrorCodeMap.put(20503, "关系错误，user_id必须是你关注的用户");
        WeiboErrorCodeMap.put(20504, "你不能关注自己");
        WeiboErrorCodeMap.put(20505, "加关注请求超过上限");
        WeiboErrorCodeMap.put(20506, "已经关注此用户");
        WeiboErrorCodeMap.put(20507, "需要输入验证码");
        WeiboErrorCodeMap.put(20508, "根据对方的设置，你不能进行此操作");
        WeiboErrorCodeMap.put(20509, "悄悄关注个数到达上限");
        WeiboErrorCodeMap.put(20510, "不是悄悄关注人");
        WeiboErrorCodeMap.put(20511, "已经悄悄关注此用户");
        WeiboErrorCodeMap.put(20512, "你已经把此用户加入黑名单，加关注前请先解除");
        WeiboErrorCodeMap.put(20513, "你的关注人数已达上限");
        WeiboErrorCodeMap.put(20521, "hi超人，你今天已经关注很多喽，接下来的时间想想如何让大家都来关注你吧！");
        WeiboErrorCodeMap.put(20522, "还未关注此用户");
        WeiboErrorCodeMap.put(20523, "还不是粉丝");
        WeiboErrorCodeMap.put(20524, "hi超人，你今天已经取消关注很多喽，接下来的时间想想如何让大家都来关注你吧！");
        WeiboErrorCodeMap.put(20525, "已经是密友了");
        WeiboErrorCodeMap.put(20526, "已经发送过密友邀请");
        WeiboErrorCodeMap.put(20527, "密友数到达上限");
        WeiboErrorCodeMap.put(20528, "不是密友");
        WeiboErrorCodeMap.put(20601, "列表名太长，请确保输入的文本不超过10个字符");
        WeiboErrorCodeMap.put(20602, "列表描叙太长，请确保输入的文本不超过70个字符");
        WeiboErrorCodeMap.put(20603, "列表不存在");
        WeiboErrorCodeMap.put(20604, "不是对象所属者");
        WeiboErrorCodeMap.put(20606, "记录已存在");
        WeiboErrorCodeMap.put(20607, "错误:数据库错误，请联系系统管理员");
        WeiboErrorCodeMap.put(20608, "列表名冲突");
        WeiboErrorCodeMap.put(20610, "目前不支持私有分组");
        WeiboErrorCodeMap.put(20611, "创建list失败");
        WeiboErrorCodeMap.put(20612, "目前只支持私有分组");
        WeiboErrorCodeMap.put(20613, "错误:不能创建更多的列表");
        WeiboErrorCodeMap.put(20614, "已拥有列表上下，请参考API文档");
        WeiboErrorCodeMap.put(20615, "成员上线，请参考API文档");
        WeiboErrorCodeMap.put(20616, "不支持的分组类型");
        WeiboErrorCodeMap.put(20617, "最大返回300条");
        WeiboErrorCodeMap.put(20618, "uid 不在列表中");
        WeiboErrorCodeMap.put(20701, "不能提交相同的标签");
        WeiboErrorCodeMap.put(20702, "最多两个标签");
        WeiboErrorCodeMap.put(20704, "您已经收藏了此微博");
        WeiboErrorCodeMap.put(20705, "此微博不是您的收藏");
        WeiboErrorCodeMap.put(20706, "操作失败");
        WeiboErrorCodeMap.put(20801, "trend_name是空值");
        WeiboErrorCodeMap.put(20802, "trend_id是空值");
        WeiboErrorCodeMap.put(21001, "标签参数为空");
        WeiboErrorCodeMap.put(21002, "标签名太长，请确保每个标签名不超过14个字符");
        WeiboErrorCodeMap.put(21101, "参数domain错误");
        WeiboErrorCodeMap.put(21102, "该手机号已经被使用");
        WeiboErrorCodeMap.put(21103, "该用户已经绑定手机");
        WeiboErrorCodeMap.put(21104, "verifier错误");
        WeiboErrorCodeMap.put(21105, "你的手机号近期频繁绑定过多个帐号，如果想要继续绑定此帐号，请拨打客服电话400 690 0000申请绑定");
        WeiboErrorCodeMap.put(21108, "原始密码错误");
        WeiboErrorCodeMap.put(21109, "新密码错误");
        WeiboErrorCodeMap.put(21110, "此用户暂时没有绑定手机");
        WeiboErrorCodeMap.put(21111, "教育信息过多");
        WeiboErrorCodeMap.put(21112, "学校不存在");
        WeiboErrorCodeMap.put(21113, "教育信息不存在");
        WeiboErrorCodeMap.put(21114, "没有用户有教育信息");
        WeiboErrorCodeMap.put(21115, "职业信息不存在");
        WeiboErrorCodeMap.put(21116, "没有用户有职业信息");
        WeiboErrorCodeMap.put(21117, "此用户没有qq信息");
        WeiboErrorCodeMap.put(21118, "学校已存在");
        WeiboErrorCodeMap.put(21119, "没有合法的uid");
        WeiboErrorCodeMap.put(21120, "此用户没有微号信息");
        WeiboErrorCodeMap.put(21121, "此微号已经存在");
        WeiboErrorCodeMap.put(21122, "用户手机绑定状态为待绑定");
        WeiboErrorCodeMap.put(21123, "用户未绑定手机");
        WeiboErrorCodeMap.put(21124, "邮箱错误");
        WeiboErrorCodeMap.put(21125, "注册邮箱禁止使用新浪邮箱");
        WeiboErrorCodeMap.put(21128, "昵称已存在或非法(昵称只能支持中英文、数字、下划线或减号;昵称禁止为全数字)");
        WeiboErrorCodeMap.put(21129, "密码长度应为6到16位");
        WeiboErrorCodeMap.put(21130, "密码只允许字母，数字，键盘半角字符");
        WeiboErrorCodeMap.put(21131, "发送激活邮件失败");
        WeiboErrorCodeMap.put(21132, "注册邮箱已被占用");
        WeiboErrorCodeMap.put(21133, "注册后激活失败");
        WeiboErrorCodeMap.put(21134, "更改用户type失败");
        WeiboErrorCodeMap.put(21135, "昵称长度应为4到30位");
        WeiboErrorCodeMap.put(21136, "gender参数可选值，m表示男性，f表示女性");
        WeiboErrorCodeMap.put(21137, "参数ip无效");
        WeiboErrorCodeMap.put(21138, "参数key不是有效的无线号段");
        WeiboErrorCodeMap.put(21140, "此用户不是会员用户");
        WeiboErrorCodeMap.put(21141, "有重复的屏蔽词");
        WeiboErrorCodeMap.put(21142, "屏蔽词个数达到当前会员类型上限");
        WeiboErrorCodeMap.put(21301, "认证失败");
        WeiboErrorCodeMap.put(21302, "用户名或密码不正确");
        WeiboErrorCodeMap.put(21303, "用户名密码认证超过请求限制");
        WeiboErrorCodeMap.put(21304, "版本号错误");
        WeiboErrorCodeMap.put(21305, "缺少必要的参数");
        WeiboErrorCodeMap.put(21306, "Oauth参数被拒绝");
        WeiboErrorCodeMap.put(21307, "时间戳不正确");
        WeiboErrorCodeMap.put(21308, "nonce参数已经被使用");
        WeiboErrorCodeMap.put(21309, "签名算法不支持");
        WeiboErrorCodeMap.put(21310, "签名值不合法");
        WeiboErrorCodeMap.put(21311, "consumer_key不存在");
        WeiboErrorCodeMap.put(21312, "consumer_key不合法");
        WeiboErrorCodeMap.put(21313, "consumer_key缺失");
        WeiboErrorCodeMap.put(21314, "Token已经被使用");
        WeiboErrorCodeMap.put(21315, "Token已经过期");
        WeiboErrorCodeMap.put(21316, "Token不合法");
        WeiboErrorCodeMap.put(21317, "Token不合法");
        WeiboErrorCodeMap.put(21318, "Pin码认证失败");
        WeiboErrorCodeMap.put(21319, "授权关系已经被解除");
        WeiboErrorCodeMap.put(21320, "不支持的协议");
        WeiboErrorCodeMap.put(21321, "未审核的应用使用人数超过限制");
        WeiboErrorCodeMap.put(21322, "重定向地址不匹配");
        WeiboErrorCodeMap.put(21323, "请求不合法");
        WeiboErrorCodeMap.put(21324, "client_id或client_secret参数无效");
        WeiboErrorCodeMap.put(21325, "提供的Access Grant是无效的、过期的或已撤销的");
        WeiboErrorCodeMap.put(21326, "客户端没有权限");
        WeiboErrorCodeMap.put(21327, "token过期");
        WeiboErrorCodeMap.put(21328, "不支持的 GrantType");
        WeiboErrorCodeMap.put(21329, "不支持的 ResponseType");
        WeiboErrorCodeMap.put(21330, "用户或授权服务器拒绝授予数据访问权限");
        WeiboErrorCodeMap.put(21331, "服务暂时无法访问");
        WeiboErrorCodeMap.put(21332, "access_token 无效");
        WeiboErrorCodeMap.put(21333, "禁止使用此认证方式");
        WeiboErrorCodeMap.put(21334, "帐号状态不正常");
        WeiboErrorCodeMap.put(21501, "access_token 无效");
        WeiboErrorCodeMap.put(21502, "禁止使用此认证方式");
        WeiboErrorCodeMap.put(21503, "IP是空值");
        WeiboErrorCodeMap.put(21504, "参数url是空值");
        WeiboErrorCodeMap.put(21601, "系统繁忙请重试");
        WeiboErrorCodeMap.put(21602, "找不到模板ID XXX");
        WeiboErrorCodeMap.put(21603, "修改数据报错");
        WeiboErrorCodeMap.put(21604, "已有通知的appkey校验失败");
        WeiboErrorCodeMap.put(21605, "创建模板超过最大限制");
        WeiboErrorCodeMap.put(21610, "授权失败");
        WeiboErrorCodeMap.put(21611, "非法appkey");
        WeiboErrorCodeMap.put(21612, "无效IP");
        WeiboErrorCodeMap.put(21613, "参数错误，需要通知id或者标题内容参数");
        WeiboErrorCodeMap.put(21620, "参数错误，uid参数必须与登录用户一致，授权用户uid %s 参数uid %s");
        WeiboErrorCodeMap.put(21621, "appkey62无效");
        WeiboErrorCodeMap.put(21631, "添加屏蔽达到上限");
        WeiboErrorCodeMap.put(21632, "禁止添加未授权的应用");
        WeiboErrorCodeMap.put(21633, "此应用没有发通知权限，不许屏蔽");
        WeiboErrorCodeMap.put(21634, "已经屏蔽过了");
        WeiboErrorCodeMap.put(21650, "未找到通知id");
        WeiboErrorCodeMap.put(21651, "只有appkey所有人能发通知");
        WeiboErrorCodeMap.put(21652, "通知模板状态不对，不能发送");
        WeiboErrorCodeMap.put(21653, "通知模板与发送通知appkey不一致");
        WeiboErrorCodeMap.put(21654, "通知发送失败，请重试");
        WeiboErrorCodeMap.put(21655, "通知请求非法");
        WeiboErrorCodeMap.put(21656, "通知模板与发送通知变量不匹配");
        WeiboErrorCodeMap.put(21701, "提醒失败，需要权限");
        WeiboErrorCodeMap.put(21702, "无效分类");
        WeiboErrorCodeMap.put(21703, "无效状态码");
        WeiboErrorCodeMap.put(21901, "地理信息接口系统错误");
        WeiboErrorCodeMap.put(21902, "地理信息接口缺少source (ip) 参数");
        WeiboErrorCodeMap.put(21903, "地理信息接口不返回任何数据");
        WeiboErrorCodeMap.put(21904, "地理信息接口ip所对应的城市不存在");
        WeiboErrorCodeMap.put(21905, "地理信息接口ip地址非法");
        WeiboErrorCodeMap.put(21906, "地理信息接口经纬度坐标非法");
        WeiboErrorCodeMap.put(21907, "地理信息接口坐标超出范围");
        WeiboErrorCodeMap.put(21908, "地理信息接口超过最大请求数");
        WeiboErrorCodeMap.put(21909, "地理信息接口远程服务错误");
        WeiboErrorCodeMap.put(21910, "地理信息接口需至少提交一个城市或中心坐标参数");
        WeiboErrorCodeMap.put(21911, "地理信息接口需至少提交一个起点id或起点坐标参数");
        WeiboErrorCodeMap.put(21912, "地理信息接口需至少提交一个终点id或终点坐标参数");
        WeiboErrorCodeMap.put(21913, "地理信息接口起点坐标非法");
        WeiboErrorCodeMap.put(21914, "地理信息接口终点坐标非法");
        WeiboErrorCodeMap.put(21915, "地理信息接口起点id非法");
        WeiboErrorCodeMap.put(21916, "地理信息接口终点id非法");
        WeiboErrorCodeMap.put(21917, "地理信息接口起点和终点在不同的城市");
        WeiboErrorCodeMap.put(21918, "地理信息接口城市代码非法");
        WeiboErrorCodeMap.put(21920, "地理信息接口创建日志目录失败");
        WeiboErrorCodeMap.put(21921, "地理信息接口查询数据不能为空");
        WeiboErrorCodeMap.put(21922, "地理信息接口提交的数据格式不正确");
        WeiboErrorCodeMap.put(21923, "地理信息接口返回结果为空，没有查到相关数据");
        WeiboErrorCodeMap.put(21940, "地理信息接口所有的字段校验不能为空");
        WeiboErrorCodeMap.put(21941, "地理信息接口表单不是post方式提交");
        WeiboErrorCodeMap.put(21942, "地理信息接口数据库出错级别");
        WeiboErrorCodeMap.put(21943, "地理信息接口scrid不存在");
        WeiboErrorCodeMap.put(21944, "地理信息接口参数超出最大小值");
        WeiboErrorCodeMap.put(21945, "地理信息接口参数不是指定类型");
        WeiboErrorCodeMap.put(21951, "地理信息接口图片尺寸超出范围");
        WeiboErrorCodeMap.put(21952, "地理信息接口图片尺寸非法");
        WeiboErrorCodeMap.put(21953, "地理信息接口中心坐标非法");
        WeiboErrorCodeMap.put(21954, "地理信息接口点的名称必须存在");
        WeiboErrorCodeMap.put(21955, "地理信息接口点的图标必须存在");
        WeiboErrorCodeMap.put(21956, "地理信息接口点的名称非法");
        WeiboErrorCodeMap.put(21957, "地理信息接口点的图标非法");
        WeiboErrorCodeMap.put(21958, "地理信息接口点的坐标非法");
        WeiboErrorCodeMap.put(21959, "地理信息接口点的图标非法");
        WeiboErrorCodeMap.put(21960, "地理信息接口需至少提交一个关键字或位置分类参数");
        WeiboErrorCodeMap.put(21961, "地理信息接口页码超出范围");
        WeiboErrorCodeMap.put(21962, "地理信息接口每页的结果数超出范围");
        WeiboErrorCodeMap.put(21963, "地理信息接口需至少提交一个坐标ID或坐标经纬度参数");
        WeiboErrorCodeMap.put(21964, "地理信息接口查询半径超出范围");
        WeiboErrorCodeMap.put(21965, "地理信息接口位置ID非法");
        WeiboErrorCodeMap.put(21966, "地理信息接口缺少参数coordinates");
        WeiboErrorCodeMap.put(21971, "地理信息接口中心坐标超出范围");

    }
    
    
    public static String getErrorMsg(Integer errorCode) {
        String message = WeiboErrorCodeMap.get(errorCode);
        if (StringUtils.isEmpty(message)) {
            message = "";
        }
        
        return message;
    }
}
